CREATE TABLE "tr_member_account" (
  "ID" int(28) NOT NULL AUTO_INCREMENT COMMENT '主键(自增处理)',
  "MEMBER_ID" varchar(32) NOT NULL COMMENT '会员编号',
  "ORIGINAL_REQUEST_NO" varchar(64) NOT NULL COMMENT '开户接口请求号(由seq_remote_request_no生成)',
  "ACCOUNT_TYPE" decimal(8,0) DEFAULT NULL COMMENT '账户类型',
  "ACCOUNT_ID" varchar(50) DEFAULT NULL COMMENT '账户编号',
  "ACCOUNT_ATTRIBUTE" decimal(8,0) NOT NULL COMMENT '账户属性(1:对私 2:对公)',
  "STATUS" decimal(8,0) NOT NULL COMMENT '状态状态(0:未激活 1:正常 2:锁定 3:止出 4:止入)',
  "ALIAS" varchar(256) DEFAULT NULL COMMENT '账户别名',
  "CREATE_TIME" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立时间',
  "UPDATE_TIME" timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '更新时间',
  "CREATE_USER" varchar(50) DEFAULT NULL COMMENT '建立人',
  "UPDATE_USER" varchar(50) DEFAULT NULL COMMENT '更新人',
  "MEMO" varchar(255) DEFAULT NULL COMMENT '备注',
  "CATEGORY" varchar(64) DEFAULT 'DPM' COMMENT '类别: DPM,CREDIT,默认为 DPM',
  "TYPE_ID" varchar(64) DEFAULT NULL COMMENT '类型id',
  "BANK_ACCOUNT_ID" varchar(32) DEFAULT NULL COMMENT '关联银行卡的Id',
  "OUTSIDE_ACCOUNT_IDENTITY" varchar(32) DEFAULT NULL COMMENT '外部账户标识',
  PRIMARY KEY ("ID"),
  UNIQUE KEY "AK_KEY_MBR_REQ" ("ORIGINAL_REQUEST_NO"),
  KEY "AK_KEY_ACCT_ID" ("ACCOUNT_ID"),
  KEY "AK_KEY_MEMBER_ID" ("MEMBER_ID"),
  KEY "IDX_MEMBERID_ACCOUNTTYPE" ("MEMBER_ID","ACCOUNT_TYPE"),
  KEY "IDX_TR_MEMBER_ACCT_CREATETIME" ("CREATE_TIME")
) ENGINE=InnoDB AUTO_INCREMENT=49988896 DEFAULT CHARSET=utf8 COMMENT='会员账户信息表';

CREATE TABLE "tm_member_identity" (
  "MEMBER_ID" varchar(32) NOT NULL COMMENT '会员编号',
  "IDENTITY" varchar(50) NOT NULL COMMENT '会员标识',
  "STATUS" decimal(8,0) NOT NULL COMMENT '1：有效；0：无效',
  "IS_RECV_ADDR" decimal(8,0) NOT NULL COMMENT '1：可以作为收款标识；0：不可以作为收款标识',
  "IDENTITY_TYPE" decimal(8,0) NOT NULL COMMENT '标识类型（0：uid 1：邮箱 2:手机 3:普通文字账号  5:商户号）',
  "CREATE_TIME" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立时间',
  "UPDATE_TIME" timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '修改时间',
  "MEMO" varchar(255) DEFAULT NULL COMMENT '备注',
  "PID" decimal(8,0) NOT NULL DEFAULT '0' COMMENT '平台类型：0:钱包平台 / 1：uid  / 2：手机号 / 3：登录名',
  PRIMARY KEY ("IDENTITY","PID"),
  KEY "IDX_IDENTITY_MEMBER_ID" ("MEMBER_ID"),
  KEY "IDX_IDENTITY_IDENTITY_AND_PID" ("IDENTITY","PID") USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='会员标识表';

CREATE TABLE "tr_verify_ref" (
  "verify_id" int(28) NOT NULL AUTO_INCREMENT COMMENT '主键(自增处理)',
  "MEMBER_ID" varchar(32) NOT NULL COMMENT '会员ID',
  "VERIFY_ENTITY_ID" decimal(28,0) NOT NULL COMMENT '认证实体ID',
  "VERIFIED_TIME" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '生效时间',
  "EXPIRE_TIME" timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '失效时间',
  "VERIFY_IMG_PATH" varchar(255) DEFAULT NULL COMMENT '认证扫描件图片路径',
  "STATUS" decimal(8,0) DEFAULT NULL COMMENT '状态(-1已解绑被删除 0未绑定 1已绑定)',
  "CREATE_TIME" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立时间',
  "UPDATE_TIME" timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '更新时间',
  "MEMO" varchar(255) DEFAULT NULL COMMENT '备注信息',
  PRIMARY KEY ("verify_id"),
  KEY "INX_TR_VERIFY_REF_ENTITY_ID" ("VERIFY_ENTITY_ID"),
  KEY "INX_TR_VERIFY_REF_MEMBER_ID" ("MEMBER_ID")
) ENGINE=InnoDB AUTO_INCREMENT=5528057 DEFAULT CHARSET=utf8 COMMENT='认证关系表';

CREATE TABLE "tr_verify_entity" (
  "verify_entity_id" int(28) NOT NULL AUTO_INCREMENT COMMENT '主键(自增处理)',
  "MEMBER_ID" varchar(32) DEFAULT NULL COMMENT '会员ID(由seq_member_id 生成, 个人1开头，企业2开头)',
  "VERIFY_TYPE" decimal(8,0) NOT NULL COMMENT '认证类型(1身份证 , 11 手机 12信箱)',
  "VERIFY_ENTITY" varchar(110) NOT NULL COMMENT '认证实体',
  "VERIFY_SUB_TYPE" decimal(8,0) DEFAULT NULL COMMENT '认证子类型',
  "CHANNEL" decimal(8,0) DEFAULT NULL COMMENT '认证渠道',
  "STATUS" decimal(8,0) DEFAULT NULL COMMENT '状态(0未认证 1已认证)',
  "CREATE_TIME" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立时间',
  "UPDATE_TIME" timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '更新时间',
  "VERIFY_SUMMARY" varchar(255) DEFAULT NULL COMMENT '认证摘要',
  "VERIFY_MEMO" varchar(255) DEFAULT NULL COMMENT '认证备注',
  PRIMARY KEY ("verify_entity_id"),
  KEY "INX_TR_VERIFY_ENTITY_TYPE" ("VERIFY_ENTITY","VERIFY_TYPE")
) ENGINE=InnoDB AUTO_INCREMENT=5467153 DEFAULT CHARSET=utf8 COMMENT='认证实体表';



CREATE TABLE "tm_operator" (
  "OPERATOR_ID" varchar(32) NOT NULL COMMENT '操作员编号(由seq_operator_id 生成,并以7开头)',
  "MEMBER_ID" varchar(32) NOT NULL COMMENT '会员ID',
  "NICKNAME" varchar(50) DEFAULT NULL COMMENT '昵称',
  "OPERATOR_TYPE" decimal(8,0) NOT NULL COMMENT '操作员类型(1个人 2企业)',
  "IS_DEFAULT" decimal(8,0) NOT NULL COMMENT '是否为默认操作员(0 否 1是)',
  "STATUS" decimal(8,0) NOT NULL COMMENT '状态(0未激活 1正常  3注销)',
  "ACTIVE_TIME" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '激活时间',
  "LOCK_STATUS" decimal(8,0) NOT NULL COMMENT '锁定状态(0未锁定 1已锁定)',
  "CREATE_TIME" timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '建立时间',
  "UPDATE_TIME" timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '更新时间',
  "CREATE_USER" varchar(50) DEFAULT NULL COMMENT '建立人',
  "UPDATE_USER" varchar(50) DEFAULT NULL COMMENT '更新人',
  "MEMO" varchar(255) DEFAULT NULL COMMENT '备注',
  "SECURITY_FLAG" decimal(8,0) DEFAULT NULL COMMENT '安全等级标记 0：默认无  1：数字证书',
  "PASSWORD" varchar(64) DEFAULT NULL COMMENT '登录密码',
  "GESTURE_PWD" varchar(64) DEFAULT NULL COMMENT '手势密码',
  "FACE_MARK_URL" varchar(256) DEFAULT NULL COMMENT '头像URL',
  "ANTI_FAKE_MARK" varchar(100) DEFAULT NULL COMMENT '防伪信息',
  PRIMARY KEY ("OPERATOR_ID"),
  KEY "IDX_OPERATOR_MEMBER_ID" ("MEMBER_ID")
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='操作员信息表';

CREATE TABLE "tr_password" (
  "ID" int(28) NOT NULL AUTO_INCREMENT COMMENT '主键(自增处理)',
  "OPERATOR_ID" varchar(32) NOT NULL COMMENT '操作员编号',
  "ACCOUNT_ID" varchar(50) NOT NULL COMMENT '账户ID',
  "password" varchar(32) DEFAULT NULL,
  "CREATE_TIME" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立时间',
  "UPDATE_TIME" timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '更新时间',
  "CREATE_USER" varchar(50) DEFAULT NULL COMMENT '建立人',
  "UPDATE_USER" varchar(50) DEFAULT NULL COMMENT '更新人',
  "MEMO" varchar(255) DEFAULT NULL COMMENT '备注信息',
  "WAP_PASSWORD" varchar(32) DEFAULT NULL COMMENT 'wap端支付密码',
  PRIMARY KEY ("ID"),
  UNIQUE KEY "AK_KEY_2_TR_PASSW" ("OPERATOR_ID","ACCOUNT_ID"),
  KEY "I_PASSWORD_ACCOUNTID" ("ACCOUNT_ID")
) ENGINE=InnoDB AUTO_INCREMENT=8843 DEFAULT CHARSET=utf8 COMMENT='会员支付密码信息表';

CREATE TABLE "tr_login_record" (
  "ID" int(28) NOT NULL AUTO_INCREMENT COMMENT '主键(自增处理)',
  "OPERATOR_ID" varchar(32) NOT NULL COMMENT '操作员编号',
  "MEMBER_ID" varchar(32) NOT NULL COMMENT '会员ID',
  "LOGIN_CHANNEL" int(1) NOT NULL COMMENT '登录渠道',
  "LOGIN_TIME" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '登录时间',
  "LOGIN_IP" varchar(50) NOT NULL COMMENT '登录IP',
  "LOGIN_STATUS" char(1) NOT NULL COMMENT '登录状态. 0 : 成功; 1: 失败.',
  "LOGIN_INFO" varchar(255) DEFAULT NULL COMMENT '登录信息',
  "EXTENTION" varchar(512) DEFAULT NULL COMMENT '扩展信息',
  "CREATE_TIME" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立时间',
  "UPDATE_TIME" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  "CREATE_USER" varchar(50) DEFAULT NULL COMMENT '建立人',
  "UPDATE_USER" varchar(50) DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY ("ID")
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='操作员登录信息表';


CREATE TABLE "tr_login_name" (
  "login_id" int(28) NOT NULL AUTO_INCREMENT COMMENT '主键(自增处理)',
  "MEMBER_ID" varchar(32) NOT NULL COMMENT '会员ID',
  "OPERATOR_ID" varchar(32) NOT NULL COMMENT '操作员编号',
  "LOGIN_NAME" varchar(50) NOT NULL COMMENT '登录名',
  "SOURCE_TYPE" decimal(8,0) NOT NULL COMMENT '来源类型(0微汇通行证)',
  "LOGIN_NAME_TYPE" decimal(8,0) NOT NULL COMMENT '登录名类型(0微汇通行证 1邮箱 2手机)',
  "UUID" varchar(50) DEFAULT NULL COMMENT '唯一编号',
  "CREATE_TIME" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立时间',
  "UPDATE_TIME" timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '更新时间',
  "CREATE_USER" varchar(50) DEFAULT NULL COMMENT '建立人',
  "UPDATE_USER" varchar(50) DEFAULT NULL COMMENT '更新人',
  "MEMO" varchar(255) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY ("login_id"),
  UNIQUE KEY "UK_MEMBER_ID_LOGIN_NAME" ("MEMBER_ID","LOGIN_NAME"),
  KEY "UK_MEMBER_ID_LOGIN_NAME_SOURCE" ("MEMBER_ID","LOGIN_NAME","SOURCE_TYPE"),
  KEY "IDX_LOGIN_OPERATOR" ("OPERATOR_ID"),
  KEY "IDX_LOGIN_SOURCE_TYPE" ("SOURCE_TYPE","LOGIN_NAME")
) ENGINE=InnoDB AUTO_INCREMENT=339405 DEFAULT CHARSET=utf8 COMMENT='操作员登录名信息表';