CREATE TABLE "tm_member_identity" (
  "MEMBER_ID" varchar(32) NOT NULL COMMENT '会员编号',
  "IDENTITY" varchar(50) NOT NULL COMMENT '会员标识',
  "STATUS" decimal(8,0) NOT NULL COMMENT '1：有效；0：无效',
  "IS_RECV_ADDR" decimal(8,0) NOT NULL COMMENT '1：可以作为收款标识；0：不可以作为收款标识',
  "IDENTITY_TYPE" decimal(8,0) NOT NULL COMMENT '标识类型（0：uid 1：邮箱 2:手机 3:普通文字账号  5:商户号）',
  "CREATE_TIME" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立时间',
  "UPDATE_TIME" timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '修改时间',
  "MEMO" varchar(255) DEFAULT NULL COMMENT '备注',
  "PID" decimal(8,0) NOT NULL DEFAULT '0' COMMENT '平台类型：0:钱包平台 / 1：uid  / 2：手机号 / 3：登录名',
  PRIMARY KEY ("IDENTITY","PID"),
  KEY "IDX_IDENTITY_MEMBER_ID" ("MEMBER_ID"),
  KEY "IDX_IDENTITY_IDENTITY_AND_PID" ("IDENTITY","PID") USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='会员标识表';

CREATE TABLE "tr_verify_ref" (
  "verify_id" int(28) NOT NULL AUTO_INCREMENT COMMENT '主键(自增处理)',
  "MEMBER_ID" varchar(32) NOT NULL COMMENT '会员ID',
  "VERIFY_ENTITY_ID" decimal(28,0) NOT NULL COMMENT '认证实体ID',
  "VERIFIED_TIME" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '生效时间',
  "EXPIRE_TIME" timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '失效时间',
  "VERIFY_IMG_PATH" varchar(255) DEFAULT NULL COMMENT '认证扫描件图片路径',
  "STATUS" decimal(8,0) DEFAULT NULL COMMENT '状态(-1已解绑被删除 0未绑定 1已绑定)',
  "CREATE_TIME" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立时间',
  "UPDATE_TIME" timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '更新时间',
  "MEMO" varchar(255) DEFAULT NULL COMMENT '备注信息',
  PRIMARY KEY ("verify_id"),
  KEY "INX_TR_VERIFY_REF_ENTITY_ID" ("VERIFY_ENTITY_ID"),
  KEY "INX_TR_VERIFY_REF_MEMBER_ID" ("MEMBER_ID")
) ENGINE=InnoDB AUTO_INCREMENT=5528057 DEFAULT CHARSET=utf8 COMMENT='认证关系表';

CREATE TABLE "tr_verify_entity" (
  "verify_entity_id" int(28) NOT NULL AUTO_INCREMENT COMMENT '主键(自增处理)',
  "MEMBER_ID" varchar(32) DEFAULT NULL COMMENT '会员ID(由seq_member_id 生成, 个人1开头，企业2开头)',
  "VERIFY_TYPE" decimal(8,0) NOT NULL COMMENT '认证类型(1身份证 , 11 手机 12信箱)',
  "VERIFY_ENTITY" varchar(110) NOT NULL COMMENT '认证实体',
  "VERIFY_SUB_TYPE" decimal(8,0) DEFAULT NULL COMMENT '认证子类型',
  "CHANNEL" decimal(8,0) DEFAULT NULL COMMENT '认证渠道',
  "STATUS" decimal(8,0) DEFAULT NULL COMMENT '状态(0未认证 1已认证)',
  "CREATE_TIME" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立时间',
  "UPDATE_TIME" timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '更新时间',
  "VERIFY_SUMMARY" varchar(255) DEFAULT NULL COMMENT '认证摘要',
  "VERIFY_MEMO" varchar(255) DEFAULT NULL COMMENT '认证备注',
  PRIMARY KEY ("verify_entity_id"),
  KEY "INX_TR_VERIFY_ENTITY_TYPE" ("VERIFY_ENTITY","VERIFY_TYPE")
) ENGINE=InnoDB AUTO_INCREMENT=5467153 DEFAULT CHARSET=utf8 COMMENT='认证实体表';