project:
  name: payment
  author: wxj

db:
  dataSource:
    url: jdbc:mysql://127.0.0.1:3306/do_payment?useUnicode=true&characterEncoding=utf8
    user: root
    password: root
  table:
    prefix:
      - tp_
    name:
    # 依次为：表名,业务主键字段(如果也是表主键就不用)
#      - tp_payment,payment_id
      - tp_pay_order,order_id
#      - tp_fund_detail,detail_id
      - tp_order_extension,order_id